-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 19:54:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rentalcar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rentalcar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rentalcar` DEFAULT CHARACTER SET utf8 ;
USE `rentalcar` ;

-- -----------------------------------------------------
-- Table `rentalcar`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_uf` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `regiao` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uf_UNIQUE` (`uf` ASC));


-- -----------------------------------------------------
-- Table `rentalcar`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_cidade` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_cidade_idx` (`uf` ASC),
  CONSTRAINT `fk_estado_cidade`
    FOREIGN KEY (`uf`)
    REFERENCES `rentalcar`.`estado` (`uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rentalcar`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `rg` VARCHAR(14) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `rua` VARCHAR(90) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `fk_cidade` INT NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo_telefone` VARCHAR(9) NOT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_cidade_funcionario_idx` (`fk_cidade` ASC),
  CONSTRAINT `fk_cidade_funcionario`
    FOREIGN KEY (`fk_cidade`)
    REFERENCES `rentalcar`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `rentalcar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `privilegios` VARCHAR(45) NOT NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_funcionario` INT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_funcionario_usuario_idx` (`fk_funcionario` ASC),
  UNIQUE INDEX `fk_funcionario_UNIQUE` (`fk_funcionario` ASC),
  CONSTRAINT `fk_funcionario_usuario`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `rentalcar`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `rentalcar`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`plano` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome_plano` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  `data_contratado` DATETIME NULL,
  `data_vencimento` DATETIME NULL,
  `qtd_veiculos` INT NOT NULL,
  `qtd_alugueis` INT NOT NULL,
  `qtd_funcionarios` INT NOT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_plano`));


-- -----------------------------------------------------
-- Table `rentalcar`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(100) NOT NULL,
  `razao_social` VARCHAR(100) NOT NULL,
  `rua` VARCHAR(90) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `fk_cidade` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `slogan` VARCHAR(45) NULL,
  `inscricao_estadual` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `fk_plano` INT NOT NULL DEFAULT 1,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo_telefone` VARCHAR(9) NOT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_empresa`),
  INDEX `fk_plano_contratado_empresa_idx` (`fk_plano` ASC),
  INDEX `fk_cidade_empresa_idx` (`fk_cidade` ASC),
  CONSTRAINT `fk_plano_contratado_empresa`
    FOREIGN KEY (`fk_plano`)
    REFERENCES `rentalcar`.`plano` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cidade_empresa`
    FOREIGN KEY (`fk_cidade`)
    REFERENCES `rentalcar`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `rentalcar`.`marca_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`marca_veiculo` (
  `id_marca_veiculo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_marca_veiculo`));


-- -----------------------------------------------------
-- Table `rentalcar`.`modelo_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`modelo_veiculo` (
  `id_modelo_veiculo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fk_marca` INT NOT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_modelo_veiculo`),
  INDEX `fk_marca_veiculo_veiculo_idx` (`fk_marca` ASC),
  CONSTRAINT `fk_marca_veiculo_veiculo`
    FOREIGN KEY (`fk_marca`)
    REFERENCES `rentalcar`.`marca_veiculo` (`id_marca_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentalcar`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `tipo_categoria` VARCHAR(45) NOT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_categoria`));


-- -----------------------------------------------------
-- Table `rentalcar`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `chassi` VARCHAR(45) NOT NULL,
  `renavam` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `fk_marca` INT NOT NULL,
  `fk_modelo` INT NOT NULL,
  `fk_categoria` INT NOT NULL,
  `ativo` INT NOT NULL DEFAULT 1,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_veiculo`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  INDEX `fk_marca_veiculo_idx` (`fk_marca` ASC),
  INDEX `fk_modelo_veiculo_idx` (`fk_modelo` ASC),
  INDEX `fk_categoria_veiculo_idx` (`fk_categoria` ASC),
  CONSTRAINT `fk_marca_veiculo`
    FOREIGN KEY (`fk_marca`)
    REFERENCES `rentalcar`.`marca_veiculo` (`id_marca_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo_veiculo`
    FOREIGN KEY (`fk_modelo`)
    REFERENCES `rentalcar`.`modelo_veiculo` (`id_modelo_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_veiculo`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `rentalcar`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `rentalcar`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`ocorrencia` (
  `id_ocorrencia` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `data_ocorrencia` DATE NOT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_ocorrencia`));


-- -----------------------------------------------------
-- Table `rentalcar`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo_telefone` VARCHAR(9) NOT NULL,
  `cnh` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `rua` VARCHAR(90) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `fk_cidade` INT NOT NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_cidade_cliente_idx` (`fk_cidade` ASC),
  CONSTRAINT `fk_cidade_cliente`
    FOREIGN KEY (`fk_cidade`)
    REFERENCES `rentalcar`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `rentalcar`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentalcar`.`aluguel` (
  `id_aluguel` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_prevista_devolucao` DATE NOT NULL,
  `data_devolucao` DATE NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_devolucao` TIME NULL,
  `cancelado` INT NOT NULL DEFAULT 0,
  `observacao` VARCHAR(100) NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  `multa` INT NOT NULL DEFAULT 0,
  `valor_multa` DECIMAL(11,2) NULL,
  `entregue` INT NOT NULL DEFAULT 0,
  `pago` INT NOT NULL,
  `data_cadastrado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_veiculo` INT NOT NULL,
  `fk_cliente` INT NOT NULL,
  `tem_ocorrencia` INT NOT NULL DEFAULT 0,
  `fk_ocorrencia` INT NULL,
  `lixo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_aluguel`),
  INDEX `fk_ocorrencia_aluguel_idx` (`fk_ocorrencia` ASC),
  INDEX `fk_veiculo_aluguel_idx` (`fk_veiculo` ASC),
  INDEX `fk_cliente_aluguel_idx` (`fk_cliente` ASC),
  CONSTRAINT `fk_ocorrencia_aluguel`
    FOREIGN KEY (`fk_ocorrencia`)
    REFERENCES `rentalcar`.`ocorrencia` (`id_ocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_aluguel`
    FOREIGN KEY (`fk_veiculo`)
    REFERENCES `rentalcar`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_aluguel`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `rentalcar`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `rentalcar`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `rentalcar`;
INSERT INTO `rentalcar`.`usuario` (`id_usuario`, `login`, `senha`, `privilegios`, `data_cadastro`, `fk_funcionario`, `lixo`) VALUES (1, 'admin', '1234567890', 'admin', DEFAULT, null, DEFAULT);

COMMIT;

